package vn.microtec.mschool.domain.enums;

public enum SystemConfigKey {
    AI_FIQA_MIN_SCORE,
    AI_SIMILARITY_THRESHOLD,
    GATE_COOLDOWN_SECONDS,
    MORNING_LATE_CUTOFF,
    AFTERNOON_DEPARTURE_START,
    NOTIF_ZNS_ENABLED,
    NOTIF_SMS_ENABLED,
    NOTIF_APP_PUSH_ENABLED,
    SNAPSHOT_RETENTION_DAYS,
    STRANGER_RETENTION_HOURS,
    CAMERA_SUBNET,
    CAMERA_RTSP_CREDENTIALS,
    CAMERA_PROBE_PORTS,
    CAMERA_PROBE_TIMEOUT_MS,
    RTSP_TEMPLATE_HIKVISION,
    RTSP_TEMPLATE_DAHUA,
    RTSP_TEMPLATE_UNIVIEW,
    RTSP_TEMPLATE_TIANDY,
    RTSP_TEMPLATE_GENERIC_ONVIF
}
