// ==============================================================================
// MSCHOOL UNIFIED ENUMS (FRONTEND & BACKEND SYNCHRONIZED)
// 100% Zero-Hardcode, Type-Safe, Không so sánh chuỗi tự do
// ==============================================================================

export enum AttendanceStatus {
  PRESENT = 'PRESENT',
  LATE = 'LATE',
  EARLY_LEAVE = 'EARLY_LEAVE',
  ABSENT = 'ABSENT',
}

export enum Direction {
  IN = 'IN',
  OUT = 'OUT',
}

export enum SubjectType {
  STUDENT = 'STUDENT',
  TEACHER = 'TEACHER',
  STAFF = 'STAFF',
  VISITOR = 'VISITOR',
}

export enum VisitorType {
  PARENT = 'PARENT',
  GUEST = 'GUEST',
  CONTRACTOR = 'CONTRACTOR',
}

export enum VisitorStatus {
  APPROVED = 'APPROVED',
  PENDING = 'PENDING',
  CHECKED_IN = 'CHECKED_IN',
  EXPIRED = 'EXPIRED',
  REVOKED = 'REVOKED',
}

export enum CameraStatus {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
}

export enum TripwireDirection {
  CHECK_IN = 'CHECK_IN',
  CHECK_OUT = 'CHECK_OUT',
  BIDIRECTIONAL = 'BIDIRECTIONAL',
}

export enum ClassroomPeriodStatus {
  FULL = 'FULL',
  MISSING = 'MISSING',
  WRONG_CLASS = 'WRONG_CLASS',
  SUBSTITUTE = 'SUBSTITUTE',
}

export enum AuditActionCode {
  OVERRIDE_ATTENDANCE = 'OVERRIDE_ATTENDANCE',
  CAMERA_CONFIG_UPDATE = 'CAMERA_CONFIG_UPDATE',
  VISITOR_APPROVE = 'VISITOR_APPROVE',
  VISITOR_REVOKE = 'VISITOR_REVOKE',
  SYSTEM_SYNC = 'SYSTEM_SYNC',
  CLASSROOM_PERIOD_CONFIRM = 'CLASSROOM_PERIOD_CONFIRM',
  CAMERA_AUTO_DISCOVER_ONBOARD = 'CAMERA_AUTO_DISCOVER_ONBOARD',
}

export enum CameraVendor {
  HIKVISION = 'HIKVISION',
  DAHUA = 'DAHUA',
  UNIVIEW = 'UNIVIEW',
  TIANDY = 'TIANDY',
  GENERIC_ONVIF = 'GENERIC_ONVIF',
}

export enum DiscoveryProtocol {
  ONVIF_WS_DISCOVERY = 'ONVIF_WS_DISCOVERY',
  PORT_SCAN_RTSP = 'PORT_SCAN_RTSP',
  SUBNET_ARP_SCAN = 'SUBNET_ARP_SCAN',
}

export enum DiscoveryMode {
  ALL = 'ALL',
  ONVIF = 'ONVIF',
  SUBNET_SCAN = 'SUBNET_SCAN',
}

export enum DiscoveryFilter {
  ALL = 'ALL',
  UNDECLARED = 'UNDECLARED',
  DECLARED = 'DECLARED',
}

export enum ConnectionStatus {
  CONNECTED = 'CONNECTED',
  DISCONNECTED = 'DISCONNECTED',
  TIMEOUT = 'TIMEOUT',
}

export enum WebhookStatus {
  ACTIVE = 'ACTIVE',
  FAILED = 'FAILED',
  RETRYING = 'RETRYING',
}

export enum WebhookEventType {
  ATTENDANCE_CHECKIN = 'ATTENDANCE_CHECKIN',
  ATTENDANCE_CHECKOUT = 'ATTENDANCE_CHECKOUT',
  CLASSROOM_EVALUATED = 'CLASSROOM_EVALUATED',
  STRANGER_DETECTED = 'STRANGER_DETECTED',
}

export enum AnomalyType {
  HIGH_ABSENCE_RATE = 'HIGH_ABSENCE_RATE',
  TEACHER_MISSING = 'TEACHER_MISSING',
  STRANGER_IN_CLASSROOM = 'STRANGER_IN_CLASSROOM',
}

export enum SeverityLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum OverrideReasonCategory {
  MEDICAL_NOTE = 'MEDICAL_NOTE',
  FAMILY_EMERGENCY = 'FAMILY_EMERGENCY',
  OFFICIAL_DISPATCH = 'OFFICIAL_DISPATCH',
  SYSTEM_ERROR = 'SYSTEM_ERROR',
}

export enum UserRole {
  ROLE_ADMIN = 'ROLE_ADMIN',
  ROLE_SUPERVISOR = 'ROLE_SUPERVISOR',
  ROLE_TEACHER = 'ROLE_TEACHER',
  ROLE_SECURITY_GUARD = 'ROLE_SECURITY_GUARD',
}

export enum StorageBucket {
  SNAPSHOTS = 'mschool-snapshots',
  BIOMETRICS = 'mschool-biometrics',
  EVIDENCE = 'mschool-evidence',
}

export enum TenantScope {
  DEFAULT_SCHOOL = 'a1000000-0000-0000-0000-000000000001',
  SYSTEM_ADMIN = '00000000-0000-0000-0000-000000000000',
}

export enum SecurityHeader {
  X_SCHOOL_ID = 'X-School-Id',
  X_USER_ROLE = 'X-User-Role',
  X_USER_NAME = 'X-User-Name',
  X_ASSIGNED_CLASSROOM = 'X-Assigned-Classroom',
}

export enum SystemConfigKey {
  AI_FIQA_MIN_SCORE = 'AI_FIQA_MIN_SCORE',
  AI_SIMILARITY_THRESHOLD = 'AI_SIMILARITY_THRESHOLD',
  GATE_COOLDOWN_SECONDS = 'GATE_COOLDOWN_SECONDS',
  MORNING_LATE_CUTOFF = 'MORNING_LATE_CUTOFF',
  AFTERNOON_DEPARTURE_START = 'AFTERNOON_DEPARTURE_START',
  NOTIF_ZNS_ENABLED = 'NOTIF_ZNS_ENABLED',
  NOTIF_SMS_ENABLED = 'NOTIF_SMS_ENABLED',
  NOTIF_APP_PUSH_ENABLED = 'NOTIF_APP_PUSH_ENABLED',
  SNAPSHOT_RETENTION_DAYS = 'SNAPSHOT_RETENTION_DAYS',
  STRANGER_RETENTION_HOURS = 'STRANGER_RETENTION_HOURS',
  CAMERA_SUBNET = 'CAMERA_SUBNET',
  CAMERA_RTSP_CREDENTIALS = 'CAMERA_RTSP_CREDENTIALS',
  CAMERA_PROBE_PORTS = 'CAMERA_PROBE_PORTS',
  CAMERA_PROBE_TIMEOUT_MS = 'CAMERA_PROBE_TIMEOUT_MS',
  RTSP_TEMPLATE_HIKVISION = 'RTSP_TEMPLATE_HIKVISION',
  RTSP_TEMPLATE_DAHUA = 'RTSP_TEMPLATE_DAHUA',
  RTSP_TEMPLATE_UNIVIEW = 'RTSP_TEMPLATE_UNIVIEW',
  RTSP_TEMPLATE_TIANDY = 'RTSP_TEMPLATE_TIANDY',
  RTSP_TEMPLATE_GENERIC_ONVIF = 'RTSP_TEMPLATE_GENERIC_ONVIF',
}

export enum SystemConfigGroup {
  AI = 'AI',
  ATTENDANCE = 'ATTENDANCE',
  NOTIFICATION = 'NOTIFICATION',
  STORAGE = 'STORAGE',
  CAMERA_NETWORK = 'CAMERA_NETWORK',
  GENERAL = 'GENERAL',
}

